@startuml
class Solution42 {
    main(String[])
}
Solution42 *--ParseData

ParseData -- Formatter
ParseData -- FileWriter
ParseData -- BufferedWriter
ParseData -- PrintWriter
ParseData -- BufferedReader

BufferedReader -- FileReader

class FileReader
{
data/exercise42_input.txt
data/exercise42_output.txt
}

@enduml