@startuml
class Solution41 {
    main(String[])
}

Solution41 *-- nameSorter

 class nameSorter{
 FileWriter()
 BufferedWriter()
 PrintWriter()
 File("data/exercise41_input.txt")
 Scanner()
 }

@enduml