@startuml
class Solution41 {
    main(String[])
}

Solution41 *-- nameSorter

 class File{
 data/exercise41_input.txt
 }

nameSorter -- File
nameSorter -- FileWriter
nameSorter -- BufferedWriter
nameSorter -- PrintWriter
nameSorter -- BufferedReader
nameSorter -- Scanner

class FileWriter{
data/exercise41_output1.txt
}

@enduml