@startuml
class Solution45 {
    main(String[])
}
Solution45 *--WordFinder

class WordFinder{
data
find()
}
WordFinder -- BufferedReader
WordFinder -- Scanner
WordFinder -- FileReader
WordFinder -- FileWriter
FileReader <--> FileWriter
class Scanner {
output
}
class FileReader {
outputFile
}
class FileWriter {
outputFile
}




@enduml